export const launchPost = {
  href: "/blog/0.1.0",
  title: "Farm.js v0.1.0: Stable, Integrated, and Agent-Native",
  description: "Our first stable release. Built for apps and agents.",
  author: "KinfeMichael Tariku",
  authorAvatar: "https://avatars.githubusercontent.com/u/65047246?v=4&size=96",
  authorUrl: "https://x.com/KinfishT",
  organization: "Farming Labs",
  organizationUrl: "https://github.com/farming-labs",
  date: "Sep 2026",
  dateTime: "2026-09",
  category: "Release",
} as const;

export const launchSections = [
  ["what-stable-means", "What stable means"],
  ["the-app-foundation", "The app foundation"],
  ["five-renderers-one-framework", "Five renderers"],
  ["an-integrations-ecosystem", "Integrations"],
  ["a-plugin-ecosystem-starting-with-devtools", "Plugins & DevTools"],
  ["typed-content-collections", "Content"],
  ["a-cli-that-explains-your-app", "The CLI"],
  ["built-for-agents-too", "Built for agents"],
  ["api-routes-as-mcp-tools", "MCP composition"],
  ["browser-tools-with-webmcp", "Browser WebMCP"],
  ["bring-your-agent-framework", "Agent frameworks"],
  ["agent-infrastructure", "Agent infrastructure"],
  ["built-with-farm-viby", "Built with Farm: Viby"],
  ["deploy-where-you-already-are", "Deployment"],
  ["how-we-earned-stable", "Earning stable"],
  ["try-it", "Try it"],
] as const;
